# Generated by Django 4.0.3 on 2022-04-28 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plans', '0002_meal_plan_delete_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_plan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
