# Generated by Django 4.0.3 on 2022-04-28 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_plans', '0003_alter_meal_plan_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ManyToManyField(related_name='recipes', to='recipes.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal_plan',
        ),
    ]
